name: Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ${{ matrix.os }}    
    strategy:
      max-parallel: 3
      matrix:
        os:
          - ubuntu-latest
        php_version:
          - 7.3
          - 7.4
          - 8.0
          - 8.1
        database:
          - mysql:5.6
          - mariadb:10.1
        impresscms_version:
          - 2.0.x
        composer_version:
          - 2

    services:
      mysql:
        image: ${{ matrix.database }}
        env:
          MYSQL_ROOT_PASSWORD: icms
          MYSQL_DATABASE: icms
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    name: Test - impresscms:${{ matrix.impresscms_version }}; php:${{ matrix.php_version }}; ${{ matrix.database }}; ${{ matrix.os }}; composer:${{ matrix.composer_version }};
    steps:
      - name: Checkouting project code...
        uses: actions/checkout@v3

      - name: Testing addon...
        uses: impresscms-dev/test-impresscms-addon-action@v0.1.1
        with:
          impresscms_version: ${{ matrix.impresscms_version }}
          php_version: ${{ matrix.php_version }}
          composer_version: ${{ matrix.composer_version }}
          database_type: pdo.mysql
          database_name: icms
          database_user: root
          database_password: icms
          database_port: ${{ job.services.mysql.ports['3306'] }}
